version: "3.9"

services:
  foodorderservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodorderservice
    ports:
      - "8083:8083"
    environment:
      - AUTH_SERVICE_URL=http://authservice:8066
    depends_on:
      - authservice

  authservice:
    image: hashicorp/http-echo
    container_name: authservice
    ports:
      - "8066:8066"
    command: "-listen=:8066 -text='{\"valid\":true,\"username\":\"testuser\",\"role\":\"ADMIN\"}'"
